services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: chamados-dev
    ports:
      - "5173:5173"
    volumes:
      - .:/app:cached
      - /app/node_modules
    command: npm run dev -- --host
